version: '3.8'
services:
  storm-mysql-master:
    container_name: storm-mysql-master
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: --server-id=1 --log-bin=mysql-bin --sync_binlog=1  --sql_mode=""
    restart: always
    volumes:
      - ./sql/master/storm.sql:/docker-entrypoint-initdb.d/storm.sql
      - ./docker/mysql-master.sh:/docker-entrypoint-initdb.d/master.sh
    security_opt:
      - seccomp:unconfined
    ports:
      - "3315:3306"
    networks:
      - storm
    
  storm-mysql-slave:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: storm-mysql-slave
    command: --server-id=2 --log-bin=mysql-slave-bin --read_only=1 --sql_mode=""
    restart: always
    volumes:
      - ./sql/slave/storm.sql:/docker-entrypoint-initdb.d/storm.sql
      - ./docker/mysql-slave.sh:/docker-entrypoint-initdb.d/slave.sh
    depends_on:
      - storm-mysql-master
    ports:
      - "3316:3306"
    networks:
      - storm

networks:
  storm:
    driver: bridge